#!/usr/bin/env bash
# write a Bash script that will display information about the subdomains

dns_config() {
    script=$(dig +short "$2.$1" | head -n 1)
    echo "Your subdomain $2 points to your $2 server IP: $script"
}

if [ "$#" == 1 ]; then
  dns_config "$1" "www"
  dns_config "$1" "lb-01"
  dns_config "$1" "web-01"
  dns_config "$1" "web-02"
elif [ "$#" == 2 ]; then
  dns_config "$1" "$2"
fi
