#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.example.com/new_page permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart

echo "Configuration completed."

