#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt update
sudo apt install nginx -y
sudo tee /etc/nginx/conf.d/redirect_me.conf > /dev/null <<EOT
server {
    listen 80;
    server_name _;
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
EOT
sudo systemctl restart nginx
