#!/usr/bin/env bash
# Installs nginx server
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null
string_for_replacement="location /redirect_me {\n\treturn 301 https://www.example.com;\n}"
sudo sed -i "/server_name _;/a $string_for_replacement" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# Add custom header configuration
sudo sed -i '/^http {/a \
    server_tokens off;\n\
    add_header X-Served-By $hostname;\n' /etc/nginx/nginx.conf

sudo service nginx restart
