#!/usr/bin/env bash

# Update the system
sudo apt update
sudo apt upgrade -y

# Set the correct hostname
echo "web-02" | sudo tee /etc/hostname > /dev/null
sudo sed -i "s/127.0.1.1.*/127.0.1.1\tweb-02/g" /etc/hosts

# Install Nginx
sudo apt install nginx -y

# Configure Nginx
sudo tee /etc/nginx/conf.d/custom.conf > /dev/null <<EOF
server {
   listen 80 default_server;
   listen [::]:80 default_server;

   server_name _;
   add_header X-Served-By \$hostname;

   location / {
       root /var/www/html;
       index index.html index.htm;
   }
}
EOF

# Restart Nginx
sudo systemctl restart nginx
