#!/usr/bin/env bash

printf "%-10s %-5s %-4s %-4s %-6s %-6s %-8s %-5s %-8s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "COMMAND"

ps aux --forest | awk '{ printf "%-10s %-5s %-4s %-4s %-6s %-6s %-8s %-5s %-8s\n", $1, $2, $3, $4, $5, $6, $7, $8, $NF }' | head -n 50
