#!/usr/bin/env bash

printf "%-10s %-20s %-15s %-8s %-8s %-12s %s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "COMMAND"

ps axo user,pid,%cpu,%mem,vsz,rss,command --forest | tail -n +2 | awk '{printf "%-10s %-20s %-15s %-8s %-8s %-12s %s\n", $1, $2, $3, $4, $5, $6, $7}'
